version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deskbooking
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./desk-booking-backend
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./desk-booking-ui
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
