version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: deskbooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: DeskBooking.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=deskbooking;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    depends_on:
      - postgres

volumes:
  postgres_data: 